version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql@root  # Set the root password here
      MYSQL_DATABASE: practice_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql@root"]
      interval: 10s
      timeout: 5s
      retries: 3

  spring-app:
    build: .
    container_name: spring_boot_container
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/practice_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASSWORD: mysql@root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_FORMAT_SQL: true
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_TYPE: com.zaxxer.hikari.HikariDataSource
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 50000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 300000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 900000
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 3
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 3
      LOGGING_LEVEL_COM_ZAXXER_HIKARI_HIKARICONFIG: DEBUG
      LOGGING_LEVEL_COM_ZAXXER_HIKARI: TRACE
    ports:
      - "8080:8080"
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql_data:
